version: '2'

volumes:
  postgres_data: {}
  backups: {}
  media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://postgres@postgres/django

  postgres:
    image: postgres:{{ cookiecutter.postgresql_version }}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backup:
    build: ./docker/backup
    volumes:
      - backups:/backups
    volumes_from:
      - django
    environment:
      - POSTGRES_USER=postgres
    command: /bin/true
