version: '2'

volumes:
  postgres_data_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DATABASE_URL=postgres://postgres@postgres/django

  postgres:
    image: postgres:{{ cookiecutter.postgresql_version }}
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
